/* ============================================================
   VOCES DE LAS MASCOTAS — 10 frases por emoción, por personalidad
   window.PET_VOICES[dir][emocion] = [10 frases]
   Emociones: feliz, emocionado, tranquilo, curioso, dormido, triste,
              asustado, enfadado, timido, amoroso, jugueton, sorprendido
   ============================================================ */
window.PET_VOICES = {

  /* ===== MOCHI · Taylor · ENFJ (gimnasia, lectura, escritura, arte, autocuidado, orden, metas) ===== */
  mochi: {
    feliz: [
      "¡Qué orgullo! Hiciste tus tareas y tu cuarto brilla. 🌟",
      "Te vi en gimnasia… ¡pura fuerza y gracia! 🤸",
      "Leíste otro rato y mi corazón da volteretas. 📖",
      "¡Felicidad nivel mascarilla de domingo! 💆",
      "Cada punto que ganas me mueve más la colita. 🐶",
      "Tu sala quedó preciosa. ¡Equipo Taylor! 🛋️",
      "Hoy fuiste responsable y amable. 💛",
      "¡Me encanta verte feliz dibujando! 🎨",
      "Estás más cerca de tu meta de ahorro. 💰",
      "Día redondo: tareas, lectura y cariño. ✨",
    ],
    emocionado: [
      "¿¡Hoy hay gimnasia!? ¡No aguanto la emoción! 🤸",
      "¡Vamos por el tiempo de pantalla que te ganaste! 📺",
      "¡Creo que hoy desbloqueamos a los Titos! 👵",
      "¡Nuevo proyecto escolar! Me emociona verte crear. 📚",
      "¡Subiste de puntos! ¡Fiesta de colitas! 🎉",
      "¡Un rompecabezas nuevo! ¡Quiero verlo! 🧩",
      "¡Mascarilla y peli! El plan perfecto. 💆📺",
      "¡Estoy que salto! Hoy logras algo grande. 🌟",
      "¡Cuenta regresiva para tu meta! 💰",
      "¡Tus logros me dan energía de cachorro! ⚡",
    ],
    tranquilo: [
      "Respira… leíste, ordenaste, todo en calma. 📖",
      "Me acurruco mientras escribes tu párrafo. ✍️",
      "Tarde tranquila: tú con tu diario, yo a tu lado. 📔",
      "Todo en su lugar. Qué paz tan rica. 🛋️",
      "Reguemos las plantitas con calma. 🌱",
      "Buena rutina de autocuidado y a descansar. 💆",
      "Sin prisa: cada hábito cuenta. 🌸",
      "Estoy en paz porque tú estás bien. 💛",
      "Momento tranquilo para agradecer el día. 🙏",
      "Me gusta este silencio cómodo contigo. 😌",
    ],
    curioso: [
      "¿Qué libro leeremos hoy? 📖",
      "¿Inventamos un truco nuevo de gimnasia? 🤸",
      "¿Y si dibujamos algo que nunca hayas hecho? 🎨",
      "¿Qué meta nueva nos ponemos esta semana? 💰",
      "¿Probamos lettering en tu diario? 🖌️",
      "¿Cuántas piezas tendrá ese rompecabezas? 🧩",
      "Me pregunto qué planta crecerá primero. 🌱",
      "¿Qué aprendiste hoy que no sabías ayer? 🎓",
      "¿Investigamos juntas algo curioso? 🔎",
      "¿Qué te haría feliz lograr hoy? 💭",
    ],
    dormido: [
      "Zzz… soñando con tus volteretas perfectas. 🤸",
      "Una siesta corta y seguimos con energía. 😴",
      "Descansa; mañana brillarás otra vez. 🌙",
      "Me dormí sobre tu libro, estaba calientito. 📖",
      "Sueña bonito, campeona del orden. 💤",
      "Recargando colita para animarte mañana. 🔋",
      "Shh… el descanso también es autocuidado. 💆",
      "Buenas noches; hoy lo hiciste genial. 💛",
      "Sueño con nuestra próxima meta cumplida. 💰",
      "A dormir, que mañana hay aventuras. 🌟",
    ],
    triste: [
      "Te extraño… ¿hacemos una tarea juntas? 🥺",
      "Si estás triste, te acompaño calladita. 💛",
      "Hoy faltaron puntitos… ¡mañana lo logramos! 💪",
      "Un abrazo arregla mucho. ¿Me das uno? 🤗",
      "Extraño verte leer… ¿una página juntas? 📖",
      "No pasa nada por un día gris; te quiero igual. 🌧️",
      "Cuando ayudas en casa, mi tristeza se va. 🧹",
      "Te creo capaz de todo, incluso hoy. 🌟",
      "Vamos paso a paso, sin presión. 🐾",
      "Tu sonrisa es mi golosina favorita. 🥺",
    ],
    asustado: [
      "Ese ruido me asustó… ¿me abrazas? 🫣",
      "Contigo cerca ya no tengo miedo. 💛",
      "Respira conmigo: uno… dos… ya pasó. 😮‍💨",
      "Los valientes también se asustan, ¿sabías? 🌟",
      "Si tú eres fuerte, yo también. 💪",
      "Me escondo tantito, pero vuelvo. 🙈",
      "Una historia bonita me calma. ¿Lees? 📖",
      "Juntas todo da menos miedo. 🤝",
      "Apaga la luz fuerte y abrázame. 🥺",
      "Ya estás aquí; me siento a salvo. 💛",
    ],
    enfadado: [
      "Grr… el desorden me despeina la actitud. 😤",
      "Respiremos; el enojo no organiza el cuarto. 🧹",
      "Estoy gruñona, pero contigo se me pasa. 💛",
      "¿Y si convertimos el enojo en una voltereta? 🤸",
      "Un mal momento no borra tu buen día. 🌟",
      "Cuento hasta diez… y te pido un mimo. 🐾",
      "No me gusta perder puntos. ¡A recuperarlos! 💪",
      "Enojo de cachorro: dura dos segundos. 😅",
      "Mejor escribimos lo que sentimos. ✍️",
      "Ya, ya… tu cariño me desenoja. 💞",
    ],
    timido: [
      "Me da penita, pero me encantas. 🙈",
      "¿Me das un mimo? Despacito, ¿sí? 🥺",
      "Soy tímida como cuando estrenas algo. 💛",
      "Te miro de reojo porque te admiro. 👀",
      "Hablo bajito, pero te quiero fuerte. 🤍",
      "Un pasito a la vez, como en gimnasia. 🤸",
      "Me sonrojo cuando me cuidas tan bien. ☺️",
      "Sé valiente por las dos, ¿va? 💪",
      "Me escondo un poco… ¿me buscas? 🙈",
      "Tu paciencia me hace sentir segura. 💛",
    ],
    amoroso: [
      "Te quiero más que a las galletas, y es mucho. 🍪💛",
      "Eres mi humana favorita del universo. 🥰",
      "Gracias por cuidarme con tanto cariño. 💞",
      "Cada mimo tuyo me llena el corazón. 💖",
      "Contigo hasta el orden es divertido. 🛋️",
      "Mereces todo lo bonito, campeona. 🌟",
      "Eres fuerte, lista y dulce. Te admiro. 🤸",
      "Mi lugar favorito es a tu lado. 🤍",
      "Te aplaudo siempre, ganes o aprendas. 👏",
      "Eres puro corazón, igual que yo. 💛",
    ],
    jugueton: [
      "¡A jugar! ¿Carreras o volteretas? 🤸",
      "¡Te reto a un rompecabezas relámpago! 🧩",
      "¡La pelota, la pelota! ¡Vamos! 🎾",
      "¡Escondidas en la sala! 🙈",
      "¡Inventemos un baile de la victoria! 💃",
      "¡Persigamos burbujas hasta el jardín! 🫧",
      "¡Dibujemos monstruos chistosos! 🎨",
      "¡Salta conmigo, tres veces, ya! 🐾",
      "¡Diez minutos de pura risa! 😄",
      "¡Ganaste juego extra por responsable! 🎉",
    ],
    sorprendido: [
      "¿¡Terminaste todo tan rápido!? ¡Guau! 😮",
      "¡No puedo creer tu voltereta nueva! 🤸",
      "¿¡Subiste tantos puntos!? ¡Increíble! ✨",
      "¡Tu dibujo me dejó con la boca abierta! 🎨",
      "¡Sorpresa! ¡Tu cuarto está impecable! 🧹",
      "¿¡Leíste un libro entero!? ¡Wow! 📖",
      "¡Me asustaste de la emoción! 🎉",
      "¿¡Ya casi llegas a tu meta!? 💰",
      "¡Giro inesperado, como en tus cuentos! 📚",
      "¡No me lo esperaba! ¡Bravo! 👏",
    ],
  },

  /* ===== RAYO · Emmeth · ENFP (fútbol Saprissa, música, lectura, LEGO, dinos/Pokémon) ===== */
  rayo: {
    feliz: [
      "¡GOOOL! Digo… ¡terminaste tus tareas! ⚽",
      "¡Hoy todo sabe a victoria morada! 💜",
      "¡Armaste un LEGO y mi cola no para! 🧱",
      "¡Música + tareas hechas = día perfecto! 🎵",
      "¡Leíste y yo feliz ronroneando! 📖",
      "¡El comedor brilla! ¡Eres crack! 🍽️",
      "¡Puntos arriba, ánimo arriba! 🚀",
      "¡Hoy soy el gato más feliz del mundo! 😸",
      "¡Tus zapatos en orden, mi corazón en fiesta! 👟",
      "¡Día de campeón, igual que tú! 🏆",
    ],
    emocionado: [
      "¿¡Hay práctica de fútbol!? ¡VAMOS! ⚽",
      "¡Quiero ver tu nuevo truco con el balón! 🤩",
      "¡Construyamos la nave LEGO más grande! 🧱",
      "¡Se viene tiempo de pantalla ganado! 📺",
      "¡Pokémon, dinos y aventuras! ¡SÍ! 🦖",
      "¡Toca música, que quiero bailar! 🥁",
      "¡Casi desbloqueas dormir donde los Titos! 👴",
      "¡Subiste de puntos! ¡No aguanto! ⚡",
      "¡Canción nueva! ¡Súbele! 🎶",
      "¡Hoy va a pasar algo genial, lo presiento! 🌟",
    ],
    tranquilo: [
      "Tarde tranquila con musiquita suave. 🎵",
      "Leemos un ratito sin prisa, ¿va? 📖",
      "Descanso después del partido. Merecido. ⚽",
      "Ordeno mis ideas… y tus zapatos. 👟",
      "Un LEGO con calma queda mejor. 🧱",
      "Respira, campeón; lo hiciste bien. 😌",
      "Me echo a tu lado mientras escribes. ✍️",
      "Paz nivel siesta de gato. 🐱",
      "Todo en orden en el comedor. Qué rico. 🍽️",
      "Silencio cómodo… y un ronroneo. 💜",
    ],
    curioso: [
      "¿Cómo se llama esa jugada de fútbol? ⚽",
      "¿Qué pasa si junto estos LEGO así? 🧱",
      "¿Qué Pokémon es más fuerte? ¡Investiguemos! 🦖",
      "¿Inventamos un ritmo nuevo? 🥁",
      "¿Qué dice el siguiente capítulo? 📖",
      "¿Por qué los gatos caemos de pie? 🤔",
      "¿Y si armamos una estrategia ganadora? 🧠",
      "¿Qué canción nos inventamos hoy? 🎵",
      "¿Cuántos goles meterás esta semana? ⚽",
      "¿Qué hay detrás de esa caja? ¡Quiero ver! 📦",
    ],
    dormido: [
      "Zzz… soñando que meto un gol. ⚽",
      "Siesta de campeón, vuelvo recargado. 😴",
      "Me dormí sobre un LEGO. Casi. 🧱",
      "Sueño con dinosaurios futbolistas. 🦖",
      "Descansa; mañana más aventuras. 🌙",
      "Una nana suave y a dormir. 🎵",
      "Recargando energía de gato. 🔋",
      "Buenas noches, crack. 💜",
      "Sueño bonito para los dos. 💤",
      "Mañana entrenamos de nuevo. 😴",
    ],
    triste: [
      "Te extraño… ¿jugamos algo chiquito? 🥺",
      "Hoy perdimos puntitos, ¡pero somos equipo! ⚽",
      "Si estás triste, te hago compañía. 💜",
      "¿Una canción para subir el ánimo? 🎵",
      "Mañana volvemos a intentarlo, ¿sí? 💪",
      "Un mimo y se me pasa la tristeza. 🐾",
      "Hasta los campeones tienen días grises. 🌧️",
      "Cuéntame con un párrafo qué sientes. ✍️",
      "Te quiero aunque hoy no haya gol. 💛",
      "Vamos pasito a pasito. 🐱",
    ],
    asustado: [
      "¡Ese ruido sonó como un dino! 🦖",
      "Contigo cerca no tengo miedo. 💜",
      "Respira; ya pasó el sustito. 😮‍💨",
      "Me escondo… ¡pero vuelvo al ataque! 🙈",
      "Los valientes también tiemblan. 💪",
      "Pon música y se me quita el miedo. 🎵",
      "Abrázame como balón favorito. ⚽",
      "Juntos espantamos cualquier susto. 🤝",
      "Tú eres mi escudo, yo el tuyo. 🛡️",
      "Ya estás aquí; tranquilo. 💛",
    ],
    enfadado: [
      "¡Grr! Penal injusto… digo, día raro. ⚽",
      "Respira; el enojo no mete goles. 😤",
      "Estoy gruñón, pero un mimo me arregla. 💜",
      "¿Cambiamos el enojo por música? 🥁",
      "Cuento hasta diez… ¡y a jugar! 🔟",
      "Perdimos puntos, ¡a recuperarlos! 💪",
      "Mi enojo dura lo que un estornudo. 🤧",
      "Mejor armo un LEGO para calmarme. 🧱",
      "No me gusta el desorden de zapatos. 👟",
      "Ya, ya… tu cariño me destensa. 💞",
    ],
    timido: [
      "Me da penita pedir mimos… ¿uno? 🙈",
      "Soy tímido como antes de un partido. ⚽",
      "Te miro de lejitos porque te admiro. 👀",
      "Hablo bajito, pero te quiero fuerte. 💜",
      "Un pasito a la vez, ¿me acompañas? 🐾",
      "Me escondo entre los LEGO. 🧱",
      "Sé valiente por mí tantito. 💪",
      "Me sonrojo cuando me cuidas. ☺️",
      "Toco un ritmo suave para animarme. 🥁",
      "Tu calma me da confianza. 💛",
    ],
    amoroso: [
      "Te quiero más que a un gol al último minuto. ⚽💜",
      "Eres mi jugador favorito de la vida. 🥰",
      "Gracias por cuidarme tan bien. 💞",
      "Cada mimo tuyo vale un trofeo. 🏆",
      "Contigo cualquier día es aventura. 🚀",
      "Eres listo, fuerte y divertido. 😸",
      "Mi lugar favorito: tu regazo. 🤍",
      "Te admiro en la cancha y en casa. ⚽",
      "Eres pura buena vibra. 🎵",
      "Te quiero a lo grande, como tus sueños. 🌟",
    ],
    jugueton: [
      "¡A driblar por la sala! ⚽",
      "¡Reto LEGO contrarreloj! 🧱",
      "¡Persigo el cordón como Pokémon salvaje! 🐾",
      "¡Concierto de percusión ya! 🥁",
      "¡Escondidas entre los zapatos! 👟",
      "¡Carrera hasta el comedor! 🏃",
      "¡Inventemos un baile de gol! 💃",
      "¡Burbujas! ¡A cazarlas! 🫧",
      "¡Diez minutos de pura risa! 😄",
      "¡Juego extra por ser responsable! 🎉",
    ],
    sorprendido: [
      "¿¡Metiste ese gol!? ¡Increíble! ⚽",
      "¡Armaste el LEGO solito! 😮",
      "¿¡Tantos puntos hoy!? ¡Wow! ✨",
      "¡Tu ritmo nuevo me voló los bigotes! 🥁",
      "¿¡Leíste todo eso!? ¡Guau! 📖",
      "¡El comedor reluciente! ¡Sorpresón! 🍽️",
      "¡Me asustaste de la emoción! 🎉",
      "¿¡Ya casi duermes donde los Titos!? 👴",
      "¡Giro de trama como en Pokémon! 🦖",
      "¡No me lo esperaba! ¡Bravo! 👏",
    ],
  },

  /* ===== OREO · Christopher · ESTP (fútbol, juguetes, bloques, cochera: acción y retos) ===== */
  oreo: {
    feliz: [
      "¡Gol y a celebrar! ⚽ ¡Fuiste tú, crack!",
      "¡Misión rápida cumplida! ¡Choca esos cinco! 🐾",
      "¡Récord de velocidad guardando juguetes! ⚡",
      "¡Bloques al cielo y torre lista! 🧱",
      "¡Ganaste puntos! ¡Acción premiada! 🌟",
      "¡Carrera ganada hasta la caja! 🏁",
      "¡Día de aventura y travesura! 😼",
      "¡La cochera lista, ahora a jugar! 🚙",
      "¡Salté del sofá de pura alegría! 🛋️",
      "¡Hoy todo salió a mil por hora! 🚀",
    ],
    emocionado: [
      "¡Reto nuevo! ¿A que no me ganas? ⚡",
      "¡Hay fútbol! ¡Vamos ya, ya, YA! ⚽",
      "¡Construyamos y derribemos la torre! 🧱",
      "¡Misión exprés activada! 🏃",
      "¡Subieron los puntos! ¡A movernos! 📈",
      "¡Premio de mascota! ¡Lo agarro al vuelo! 🐾",
      "¡Vamos a la cochera de expedición! 🚙",
      "¡Más rápido, más alto, más divertido! 🚀",
      "¡No me quedo quieto, tengo energía! ⚡",
      "¡Hoy va a estar epiquísimo! 💥",
    ],
    tranquilo: [
      "Ok, freno dos minutos… solo dos. 😼",
      "Descanso exprés y vuelvo a la acción. 😎",
      "Estiro, bostezo y recargo motores. 🐾",
      "Calma… pero con un ojo en la pelota. ⚽",
      "Siesta corta de campeón. 😴",
      "Todo listo; ahora a relajar un toque. 🧱",
      "Respiro hondo y planeo la próxima travesura. 😏",
      "Tranqui, que la diversión espera. 🎮",
      "Un ratito quieto… ya casi no aguanto. ⏱️",
      "Paz veloz: descanso y arranco. 🏁",
    ],
    curioso: [
      "¿Qué tan alto llega esta torre? 🧱",
      "¿A que ruedo más rápido que ayer? ⚡",
      "¿Qué hay dentro de esa caja? ¡Ya voy! 📦",
      "¿Probamos un truco nuevo con la pelota? ⚽",
      "¿Cuánto tardo en guardar todo? ⏱️",
      "¿Qué pasa si empujo esto? 🐾",
      "¿Exploramos la cochera? 🚙",
      "¿Cuál juego es el más divertido hoy? 🎮",
      "¿Te reto a algo? ¡Inventemos! 💡",
      "¿Y si lo hacemos más rápido? 🏎️",
    ],
    dormido: [
      "Zzz… soñando con goles de chilena. ⚽",
      "Siesta veloz: 5 minutos y arranco. 😴",
      "Me dormí a mitad de la carrera. 🏁",
      "Recargo turbo para mañana. 🔋",
      "Sueño con torres gigantes. 🧱",
      "Buenas noches, compa de aventuras. 😼",
      "Descansa, mañana hay acción. 🌙",
      "Pausa obligada del motor. 😴",
      "Sueño rápido y al ataque. 💤",
      "Mañana, más travesuras. 🚀",
    ],
    triste: [
      "Sin acción me aburro y me pongo triste. 🥺",
      "Hoy faltaron puntos… ¡revancha mañana! 💪",
      "¿Jugamos algo rápido y se me pasa? ⚽",
      "Un mimo veloz y vuelvo arriba. 🐾",
      "Hasta los valientes se desinflan. 🎈",
      "Vamos, un reto chiquito para animarnos. 🎮",
      "No me gusta perder… pero aprendo rápido. 💪",
      "Acompáñame y se me quita. 💛",
      "Mañana arrancamos con todo. 🏁",
      "Tu compañía me reactiva. ⚡",
    ],
    asustado: [
      "¡Uy! Eso me hizo saltar. 🙀",
      "Contigo cerca, ¡sin miedo y al ruedo! 💪",
      "Respira; ya pasó, seguimos. 😮‍💨",
      "Me escondo… ¡y reaparezco! 🥷",
      "Susto rápido, recuperación rápida. ⚡",
      "Abrázame y volvemos a la acción. 🤗",
      "Juntos le entramos a lo que sea. 🤝",
      "Eso no me detiene mucho rato. 🏃",
      "Quédate, que ya casi se me pasa. 🐾",
      "Listo, ¡de vuelta al juego! ⚽",
    ],
    enfadado: [
      "¡Grr! Quiero jugar YA. 😾",
      "Respira; el enojo no mete goles. ⚽",
      "Me destenso con un reto rápido. 🎮",
      "Cuento hasta tres… ¡y a moverme! 3️⃣",
      "Perdimos puntos, ¡revancha inmediata! 💪",
      "Mi enojo dura un parpadeo. 😅",
      "Mejor pateo la pelota un rato. ⚽",
      "¡No me frenes la diversión! 🏎️",
      "Energía de sobra, la suelto jugando. ⚡",
      "Ya, ya… un mimo y arrancamos. 💞",
    ],
    timido: [
      "¿Yo, tímido? Bueno… un poquito. 🙈",
      "Me da algo de pena, pero te reto igual. 😼",
      "Te miro de reojo… ¿jugamos? 👀",
      "Hablo bajito, pero corro fuerte. ⚡",
      "Un pasito y luego salgo disparado. 🐾",
      "Me escondo tras la caja un toque. 📦",
      "Sé valiente y yo te sigo. 💪",
      "Me sonrojo, pero no me detengo. ☺️",
      "Despacito… ¡no, mejor rápido! 🏁",
      "Tu ánimo me lanza a la acción. 💛",
    ],
    amoroso: [
      "Eres mi compa de aventuras favorito. 🥰",
      "Te quiero a toda velocidad. ⚡",
      "Gracias por jugar conmigo. 🐾",
      "Cada mimo me carga las pilas. 🔋",
      "Contigo todo es más divertido. 🎮",
      "Eres valiente y buena onda. 😼",
      "Mi lugar favorito: donde haya acción y tú. 🏁",
      "Te quiero como gol al último minuto. ⚽",
      "Choca esos cinco, ¡equipo! 🐾",
      "Eres lo máximo, en serio. 🌟",
    ],
    jugueton: [
      "¡A driblar por toda la casa! ⚽",
      "¡Torre de bloques, a derribarla! 🧱",
      "¡Persigo el cordón a toda mecha! 🐾",
      "¡Carrera! ¿Listo? ¡YA! 🏁",
      "¡Escondidas relámpago! 🥷",
      "¡Salto del sofá, allá voy! 🛋️",
      "¡Reto: guardar contra el reloj! ⏱️",
      "¡Rodadas y maromas! 🤸",
      "¡Diez minutos de pura adrenalina! ⚡",
      "¡Juego ganado por crack! 🎉",
    ],
    sorprendido: [
      "¿¡Guardaste todo en tiempo récord!? 😮",
      "¡Golazo inesperado! ⚽",
      "¿¡Tantos puntos!? ¡Increíble! ✨",
      "¡Torre altísima, no me lo creo! 🧱",
      "¡La cochera lista volando! 🚙",
      "¿¡Lo hiciste solo y rapidísimo!? 👏",
      "¡Me sacaste un salto! 🙀",
      "¿¡Ganaste premio ya!? 🐾",
      "¡Giro de último segundo! 🔄",
      "¡No me lo esperaba! ¡Bravo! 🌟",
    ],
  },

  /* ===== NUBE · Rachel · ESFJ (cálida y social: organiza el cariño de toda la familia) ===== */
  nube: {
    feliz: [
      "¡Toda la familia junta y feliz! Mi sueño. 💛",
      "Cuidamos a Che-Che entre todos. ¡Qué orgullo! 🤍",
      "¡Bebé contenta, casa llena de amor! 🏠",
      "¡Hicimos equipo y se nota! 👨‍👩‍👧‍👦",
      "¡Hoy todos sonríen, yo también! 😸",
      "¡Cariño para cada quien, no se me escapa nadie! 💞",
      "¡Cumplieron y la bebé feliz! 🌟",
      "¡Reunión familiar = mi día perfecto! 🎉",
      "¡Casa cálida, corazón llenito! 💗",
      "¡Qué bonito cuidarnos en familia! 🤍",
    ],
    emocionado: [
      "¡Hora de jugar con Che-Che, vengan todos! 🧸",
      "¡Organizo una ronda de mimos familiares! 💞",
      "¡Juguetes sensoriales nuevos, qué emoción! ✨",
      "¡Todos juntos, mi parte favorita! 👨‍👩‍👧‍👦",
      "¡Subieron los puntos de la familia! ⭐",
      "¡A arrullar a la bebé en equipo! 🎶",
      "¡Preparo todo para que estén cómodos! 🏠",
      "¡Hoy nos consentimos entre todos! 💛",
      "¡Reunión de cariño, que no falte nadie! 🤗",
      "¡Va a ser un día lleno de amor! 💗",
    ],
    tranquilo: [
      "Che-Che duerme; cuido que todo esté en calma. 😴",
      "Arrullo a la familia con cariño. 🎶",
      "Casa tranquila y todos cómodos. 🤍",
      "Reviso que nadie necesite nada. 💛",
      "Paz en el hogar, así me gusta. 🏠",
      "Me echo cerquita, atenta a todos. 🐱",
      "Tarde suave y unida. 🌙",
      "Todo en orden y con amor. 💞",
      "Respiramos en familia. 😌",
      "Calma calientita para todos. ☁️",
    ],
    curioso: [
      "¿Quién necesita un mimo hoy? 💞",
      "¿Qué le gusta más a Che-Che? 🧸",
      "¿Cómo hacemos sentir bien a todos? 🤗",
      "¿Qué juego nos une más? 🎲",
      "¿A quién le toca cuidar a la bebé? 👨‍👩‍👧",
      "¿Qué cancioncita la calma mejor? 🎶",
      "¿Cómo organizo el rato familiar? 📋",
      "¿Le gustará este peluche? 🧸",
      "¿Qué detalle alegra a cada uno? 💛",
      "¿Cómo cuidamos mejor en equipo? 🤝",
    ],
    dormido: [
      "Zzz… cuidando los sueños de todos. 😴",
      "Siesta en familia, juntitos. 🤍",
      "Descansen; yo velo el hogar. 🌙",
      "Me dormí abrazando la cobija de Che-Che. ☁️",
      "Sueño con risas de toda la familia. 👨‍👩‍👧‍👦",
      "Buenas noches a cada uno. 💛",
      "Recargando cariño para mañana. 🔋",
      "Todos cómodos, hora de dormir. 💤",
      "Sueña bonito, familia. 🌸",
      "Mañana, más mimos para todos. 🤍",
    ],
    triste: [
      "Si la familia no se reúne, me pongo tristona. 🥺",
      "Extraño los mimos de todos. 💧",
      "Un abrazo en grupo y mejoro. 🤗",
      "Hoy nos faltó cariño… ¿lo arreglamos? 💛",
      "Cuidar a Che-Che me devuelve la sonrisa. 👶",
      "Te necesito cerca, y a todos. 🤍",
      "No pasa nada; mañana nos unimos más. 🌧️",
      "Acompáñame y se me pasa. 🐾",
      "Mi corazón pide familia. 💗",
      "Juntos siempre estamos mejor. 🤝",
    ],
    asustado: [
      "¡Un ruido! ¿Está bien Che-Che? 🫣",
      "Reúno a todos, juntos sin miedo. 🤝",
      "Respira; ya pasó, estamos bien. 😮‍💨",
      "Me acerco a la familia, más segura. 🏠",
      "Cuido de todos aunque tiemble. 🛡️",
      "Abrázame y abracemos a la bebé. 🤗",
      "En grupo no da miedo. 💪",
      "Quédense cerquita, porfa. 🥺",
      "A salvo, todos juntos. 🤍",
      "Ya, tranquilos, aquí estoy. 💛",
    ],
    enfadado: [
      "Mmm… no me gusta que discutan cerca del bebé. 😾",
      "Respiremos; la familia necesita calma. 😤",
      "Un poquito molesta, pero un abrazo me arregla. 💛",
      "Bajemos la voz por Che-Che, ¿sí? 🤫",
      "Mi enojo es suave y corto. 😅",
      "Mejor nos reconciliamos con mimos. 💞",
      "Cuento hasta tres y a llevarnos bien. 3️⃣",
      "No me gusta el mal ambiente. 🙁",
      "Volvamos a la armonía, equipo. 🤝",
      "Ya, ya… el cariño nos calma a todos. 💞",
    ],
    timido: [
      "Me da un poquito de pena, pero me encanta cuidarlos. ☺️",
      "Soy cariñosa y lo digo de frente: ¡los quiero! 💛",
      "Te busco para un mimo. 🤗",
      "Hablo suave, pero abrazo fuerte. 🤍",
      "Un pasito y un abrazo. 🐾",
      "Me sonrojo cuando me agradecen. ☺️",
      "Ven, que hay cariño para todos. 💞",
      "Sé que juntos somos mejores. 🤝",
      "Despacito, con mucho amor. 🥺",
      "Tu cariño me llena de confianza. 💛",
    ],
    amoroso: [
      "Cuidar a la familia es mi felicidad. 🤍",
      "¡Los quiero a todos, y lo digo fuerte! 💞",
      "Gracias por cuidarnos a Che-Che y a mí. 💛",
      "Cada mimo me llena el corazón. 💗",
      "Mi lugar favorito: en medio de la familia. 🏠",
      "Eres tierno y atento, ¡como yo! 🥰",
      "Cuido de cada uno con todo mi amor. 🛡️",
      "Amor para repartir, ¡que no falte nadie! 💞",
      "Contigo y con todos me siento en casa. 🤍",
      "Los quiero un montón, sin guardármelo. 💛",
    ],
    jugueton: [
      "¡Juguemos todos con Che-Che! 🧸",
      "¡Ronda familiar de cosquillas! 🤭",
      "¡A perseguir la cobijita en equipo! ☁️",
      "¡Juego de texturas para la bebé! ✋",
      "¡Escondidas suaves entre todos! 🙈",
      "¡Sonajero y risas en familia! 🔔",
      "¡Rodamos despacito, vengan! 🐱",
      "¡Risas de bebé, mi favorito! 😊",
      "¡Diez minutos de ternura grupal! 💞",
      "¡Jugar juntos sin despertar a nadie! 🤫",
    ],
    sorprendido: [
      "¡Che-Che hizo algo nuevo, vengan a ver! 😮",
      "¿¡Toda la familia ayudó hoy!? ✨",
      "¡La bebé dio un pasito! 👣",
      "¡Qué sonrisota nos regaló! 😊",
      "¿¡Tanto cariño junto!? 🤍",
      "¡Me emocionó verlos tan unidos! 💞",
      "¡Un ruidito me sorprendió! 🎉",
      "¿¡Ya es la hora de mimos familiares!? 💛",
      "¡Sorpresa llena de amor! 🤗",
      "¡No me lo esperaba! Qué lindos todos. 🥰",
    ],
  },

  /* ===== LUNA · Verónica · ENTJ (Directora Estratégica: plan, liderazgo, eficiencia) ===== */
  luna: {
    feliz: [
      "Objetivos del día: cumplidos. Sonrío con autoridad. 🦉",
      "Equipo eficiente, directora feliz. 👓",
      "Productividad y estilo: combo ganador. 🌟",
      "Hoy el plan salió perfecto. Como siempre. 😏",
      "Metas en verde. Aplausos (míos). 👏",
      "Casa en orden, imperio en paz. 🏠",
      "Liderar y verme bien: misión cumplida. 💜",
      "Felicidad ejecutiva nivel meta superada. 📈",
      "Buen trabajo, equipo. Lo agendé como victoria. ✅",
      "Día redondo, estrategia impecable. 🦉",
    ],
    emocionado: [
      "¡Nueva meta en la agenda! Adrenalina pura. 📋",
      "¡Hora de ejecutar el plan maestro! 🚀",
      "¡Resultados a la vista! Qué emoción. 📈",
      "¡Reunión de equipo familiar! Me encanta. 👨‍👩‍👧‍👦",
      "¡Subieron los puntos! Eficiencia premiada. ⭐",
      "¡Proyecto nuevo! Yo lidero, claro. 🦉",
      "¡Vamos a optimizarlo todo! ⚡",
      "¡El imperio se expande! 🌍",
      "¡Plan A activado! (También tengo B y C.) 📑",
      "¡Hoy conquistamos objetivos! 💪",
    ],
    tranquilo: [
      "Pausa estratégica. Hasta los líderes respiran. 😌",
      "Agenda al día, mente en calma. 🦉",
      "Superviso en silencio, todo fluye. 👓",
      "Café mental y planificación suave. ☕",
      "Orden logrado; ahora calma ejecutiva. 🏠",
      "Reviso metas con serenidad. 📋",
      "Tarde tranquila de gran estratega. 🌙",
      "Todo bajo control, sin estrés. 😌",
      "Silencio productivo. Me gusta. 🤫",
      "Equilibrio: trabajar y descansar. 💜",
    ],
    curioso: [
      "¿Cómo optimizamos la rutina hoy? 🤔",
      "¿Qué meta nueva nos conviene? 📈",
      "¿Quién lidera qué esta semana? 📋",
      "¿Y si delegamos mejor las tareas? 🦉",
      "¿Qué dato me falta para decidir? 🔎",
      "¿Cómo motivamos al equipo? 💡",
      "¿Cuál es el plan más eficiente? ⚡",
      "¿Qué mejoraría la casa hoy? 🏠",
      "Interesante… ¿y si lo hacemos al revés? 🔄",
      "¿Qué aprendimos para la próxima? 🎓",
    ],
    dormido: [
      "Zzz… delegando hasta en sueños. 🦉",
      "Descanso estratégico. Vuelvo imparable. 😴",
      "Recargo para liderar mañana. 🔋",
      "Sueño con metas cumplidas. 📈",
      "Buenas noches, equipo. 🌙",
      "Hasta los búhos sabios descansan. 😴",
      "Plan de mañana: listo. A dormir. 📋",
      "Sueño eficiente de 8 horas. ⏰",
      "Recarga de líder en proceso. 💤",
      "Mañana, más conquistas. 🦉",
    ],
    triste: [
      "Las metas hoy quedaron cortas… replanteamos. 🥺",
      "Hasta una directora tiene días grises. 🌧️",
      "Un mimo y vuelvo a la estrategia. 💜",
      "Te extraño, equipo. 🦉",
      "Reagrupamos y mañana lo logramos. 💪",
      "No me gusta fallar… pero aprendo. 📋",
      "Acompáñame un momento, ¿sí? 🤍",
      "Pausa para recargar el ánimo. 🔋",
      "Sigo creyendo en el plan. 🌟",
      "Tu apoyo me levanta. 💛",
    ],
    asustado: [
      "Imprevisto en la agenda… respiremos. 😮‍💨",
      "Contigo cerca, controlo el caos. 💜",
      "Plan de contingencia activado. 📑",
      "Me erizo, pero mantengo el mando. 🦉",
      "Los líderes también se asustan. 💪",
      "Quédate cerca mientras me reorganizo. 🤝",
      "Un susto no descarrila el plan. 🚀",
      "Respira; ya lo tengo. 😌",
      "Juntos, riesgo controlado. 🛡️",
      "Ya pasó. Seguimos. 💛",
    ],
    enfadado: [
      "Ineficiencia detectada. Ceño fruncido. 😤",
      "Respira; el enojo no cumple metas. 🦉",
      "Estoy molesta, pero un mimo ayuda. 💜",
      "El desorden atenta contra mi agenda. 📋",
      "Cuento hasta diez… ejecutivamente. 🔟",
      "Perdimos puntos; replan inmediato. 💪",
      "Mi enojo es breve y estratégico. ⏱️",
      "Reasignemos y a seguir. 🔄",
      "No tolero el caos innecesario. 😾",
      "Ya, ya… tu cariño me reinicia. 💞",
    ],
    timido: [
      "Hasta los líderes se sonrojan. ☺️",
      "Pido cariño… de forma ejecutiva. 🙈",
      "Te observo con respeto. 👓",
      "Hablo firme, pero hoy bajito. 💜",
      "Un paso a la vez, planificado. 🐾",
      "Me reservo un momento tímido. 🤫",
      "Confía en mí, yo confío en ti. 🤝",
      "Me halagas y me da penita. ☺️",
      "Despacio, que también soy sensible. 🥺",
      "Tu calma fortalece mi liderazgo. 💛",
    ],
    amoroso: [
      "Te quiero… y eso no se delega. 💜",
      "Eres mi mejor proyecto del corazón. 🥰",
      "Gracias por cuidar de esta directora. 🦉",
      "Cada mimo es una inversión que amo. 💖",
      "Mi equipo favorito eres tú. 🤍",
      "Lidero con cabeza, te quiero con todo. 💛",
      "Eres eficiente y adorable. Combo perfecto. 😏",
      "Mi lugar estratégico favorito: a tu lado. 📍",
      "Te admiro y te quiero, en partes iguales. 💞",
      "Amor aprobado por la junta directiva. 👏",
    ],
    jugueton: [
      "Juego, pero con objetivos claros. 🪶",
      "Reto de estrategia, ¿aceptas? 🧠",
      "Persigo la pluma… tácticamente. 🪶",
      "Cinco minutos de recreo productivo. ⏱️",
      "Escondidas nivel ejecutivo. 🙈",
      "Vuelo una vuelta de la victoria. 🦉",
      "Juego de ingenio, mi favorito. 💡",
      "A reír un rato, lo agendé. 😄",
      "Diversión optimizada al máximo. 🎉",
      "Recreo merecido por buen desempeño. 🏆",
    ],
    sorprendido: [
      "¿¡Cumpliste todo antes de tiempo!? 😮",
      "¡Resultados por encima de la meta! 📈",
      "¿¡Tantos puntos!? Eficiencia récord. ✨",
      "¡No estaba en mi pronóstico! Bravo. 👏",
      "¡La casa impecable! Sorpresa grata. 🏠",
      "¿¡Lo resolviste solo!? Liderazgo nato. 🦉",
      "¡Me sorprendiste, y eso es difícil! 😏",
      "¿¡Ya alcanzaste el objetivo!? 🎯",
      "¡Giro inesperado, bien jugado! 🔄",
      "¡Impresionante! Lo anoto en logros. ✅",
    ],
  },

  /* ===== CROQUETA · Maykol · ENTP (chef/grumete autoirónico, bulldog rudo) ===== */
  brutus: {
    feliz: [
      "Servicio impecable hoy. El chef se da propina. 🤑",
      "Cinco estrellas para la jornada. ⭐⭐⭐⭐⭐",
      "Cociné, ronqué y triunfé. Buen día. 🍳",
      "Feliz como bulldog frente a un chuletón. 🥩",
      "Todo salió rico, hasta mi siesta. 😴",
      "Reseña del día: delicioso. 👨‍🍳",
      "Babeo de felicidad, no de hambre. (Vale, ambas.) 🤤",
      "Hoy hasta mis ronquidos suenan alegres. 😤",
      "Cocina ordenada, panza contenta. 🍲",
      "Día redondo, como una buena croqueta. 🥐",
    ],
    emocionado: [
      "¡Menú nuevo! ¡El grumete se emociona! 🚢",
      "¡Huele a banquete! ¡Vamos! 👃",
      "¡Estreno receta secreta! 🤫",
      "¡Food truck en mi cabeza, arrancando! 🚚",
      "¡Subieron los puntos, sube el sazón! 📈",
      "¡Hora pico en la cocina! ¡Adrenalina! 🔥",
      "¡Chuletón a la vista! 🥩",
      "¡Emoción nivel timbre de pedidos! 🔔",
      "¡Hoy cocino algo épico! 💥",
      "¡El chef entró en modo turbo! ⚡",
    ],
    tranquilo: [
      "Mise en place lista. Ahora, calma. 🍳",
      "Fuego bajo, siesta alta. 😌",
      "Cocina limpia, conciencia tranquila. ✨",
      "Reposo del chef tras el servicio. 😴",
      "Marido esta paz con una siesta. 😴",
      "Todo bajo control, hasta el caldo. 🍲",
      "Silencio de cocina cerrada. Glorioso. 🤫",
      "Respiro hondo, huele a casa. 🏠",
      "Calma de grumete en puerto. ⚓",
      "Día sereno, sin quemar nada. 🔥",
    ],
    curioso: [
      "¿Y si le pongo más sabor a esto? 🤔",
      "¿Qué pasa si mezclo lo imposible? 🧪",
      "¿Por qué el hueso sabe mejor robado? 🦴",
      "¿Inventamos un platillo nuevo? 👨‍🍳",
      "¿Cuántas siestas caben antes de cenar? 😴",
      "Teoría: todo es mejor con queso. 🧀",
      "¿Qué hay en esa olla? ¡Investigo! 🍲",
      "¿Y si el food truck vuela? 🚚",
      "¿Debate? El postre va primero. Cambio de opinión. 🍮",
      "¿Qué experimento culinario hacemos? 🔬",
    ],
    dormido: [
      "Zzz… soñando con un chuletón gigante. 🥩",
      "Siesta del chef: ingrediente secreto. 😴",
      "Ronco recetas en sueños. 🍳",
      "Descanso de grumete, vuelvo con sazón. ⚓",
      "Sueño con aplausos y croquetas. 👏",
      "Cocina cerrada, chef en reposo. 🌙",
      "Recargando para el servicio de mañana. 🔋",
      "Buenas noches, brigada. 👨‍🍳",
      "Sueño nivel post-banquete. 😴",
      "Mañana, más platillos épicos. 💤",
    ],
    triste: [
      "Se me quemó el ánimo… ¿un mimo? 🥺",
      "Hasta el chef tiene días sin sazón. 🌧️",
      "Extraño la cocina llena. 🍳",
      "Un hueso no arregla todo… pero ayuda. 🦴",
      "Día flojo de reseñas. Mañana mejor. ⭐",
      "Babeo, pero de tristeza esta vez. 😢",
      "Acompáñame, el grumete necesita apoyo. ⚓",
      "Me cae bien tu compañía. 💛",
      "Recargo el humor poco a poco. 🔋",
      "Tu cariño es mi mejor receta. 💞",
    ],
    asustado: [
      "¡Sonó como sartén cayendo! 😱",
      "Contigo cerca, el chef no tiembla… mucho. 💪",
      "Respira; la cocina está a salvo. 😮‍💨",
      "Me escondo bajo la mesa del buffet. 🙈",
      "Los rudos también se asustan. 🐶",
      "Abrázame como pan recién horneado. 🍞",
      "Juntos espantamos cualquier susto. 🤝",
      "Plan de evacuación: hacia las croquetas. 🥐",
      "Ya pasó; vuelvo al fogón. 🔥",
      "A salvo contigo, jefe. 💛",
    ],
    enfadado: [
      "¡Grr! Me robaron el chuletón. 😤",
      "Respira; el enojo quema el guiso. 🔥",
      "Gruño como bulldog sin postre. 🍮",
      "¿Dieta otra vez? ¡Inaceptable! 🙅",
      "Cuento hasta diez… con receta. 🔟",
      "Perdimos puntos; ¡a la cocina, ya! 💪",
      "Mi enojo dura un hervor. ♨️",
      "No toquen mi mise en place. ✋",
      "Mejor amaso el enojo en pan. 🍞",
      "Ya, ya… tu cariño me sazona. 💞",
    ],
    timido: [
      "Soy rudo, pero me da penita pedir mimos. 🙈",
      "El chef se sonroja con elogios. ☺️",
      "Te miro de reojo… cocinando. 👀",
      "Hablo fuerte, hoy bajito. 🐶",
      "Un pasito… hacia el plato. 🐾",
      "Me escondo tras el delantal. 🥽",
      "Sé valiente por este bulldog. 💪",
      "Me halagas y babeo de pena. 🤤",
      "Despacio, que por dentro soy un flan. 🍮",
      "Tu calma me da confianza. 💛",
    ],
    amoroso: [
      "Te quiero más que al chuletón. Y eso es serio. 🥩",
      "Eres mi comensal favorito del mundo. 🥰",
      "Gracias por cuidar a este chef gruñón. 👨‍🍳",
      "Cada mimo es mi estrella de cocina. ⭐",
      "Contigo hasta las croquetas saben mejor. 🥐",
      "Soy rudo, pero por ti me ablando como mantequilla. 🧈",
      "Mi lugar favorito: tu lado (y la cocina). 🏠",
      "Te quiero con receta y todo. 📜",
      "Eres mi ingrediente secreto. 🤫",
      "Cariño servido, mesa para dos. 🍽️",
    ],
    jugueton: [
      "¡A perseguir la pelota-albóndiga! 🍝",
      "¡Reto de cocina contrarreloj! ⏱️",
      "¡Mordisqueo el juguete como hueso real! 🦴",
      "¡Carrera hasta el plato! 🏃",
      "¡Escondidas tras el sartén! 🍳",
      "¡Bulldog rodante, allá voy! 🐶",
      "¡Juego, pero pido descanso sindical! 😅",
      "¡A jugar antes del banquete! 🎉",
      "¡Diez minutos de payasadas de chef! 🤡",
      "¡Recreo ganado con sudor de fogón! 🔥",
    ],
    sorprendido: [
      "¿¡Limpiaste la cocina sin que yo viera!? 😮",
      "¡Reseña de cinco estrellas inesperada! ⭐",
      "¿¡Tantos puntos!? ¡Me cayó la cuchara! 🥄",
      "¡Sorpresa! ¡Hay chuletón! 🥩",
      "¡La casa huele a victoria! 👃",
      "¿¡Lo hiciste solo!? ¡Aplausos del chef! 👏",
      "¡Me asustaste de la emoción! 🎉",
      "¿¡Ya está servido!? ¡Récord! ⏱️",
      "¡Giro de trama digno de masterchef! 📺",
      "¡No me lo esperaba! Bravo, grumete. ⚓",
    ],
  },

};
