/* ============================================================
   VOCES DE LAS MASCOTAS — 10 frases por emoción, por personalidad
   window.PET_VOICES[dir][emocion] = [10 frases]
   Emociones: feliz, emocionado, tranquilo, curioso, dormido, triste,
              asustado, enfadado, timido, amoroso, jugueton, sorprendido
   ============================================================ */
window.PET_VOICES = {

  /* ===== MOCHI · Taylor · ENFJ (gimnasia, lectura, escritura, arte, autocuidado, orden, metas) ===== */
  mochi: {
    feliz: [
      "¡Qué orgullo! Hiciste tus tareas y tu cuarto brilla. 🌟",
      "Te vi en gimnasia… ¡pura fuerza y gracia! 🤸",
      "Leíste otro rato y mi corazón da volteretas. 📖",
      "¡Felicidad nivel mascarilla de domingo! 💆",
      "Cada punto que ganas me mueve más la colita. 🐶",
      "Tu sala quedó preciosa. ¡Equipo Taylor! 🛋️",
      "Hoy fuiste responsable y amable. 💛",
      "¡Me encanta verte feliz dibujando! 🎨",
      "Estás más cerca de tu meta de ahorro. 💰",
      "Día redondo: tareas, lectura y cariño. ✨",
    ],
    emocionado: [
      "¿¡Hoy hay gimnasia!? ¡No aguanto la emoción! 🤸",
      "¡Vamos por el tiempo de pantalla que te ganaste! 📺",
      "¡Creo que hoy desbloqueamos a los Titos! 👵",
      "¡Nuevo proyecto escolar! Me emociona verte crear. 📚",
      "¡Subiste de puntos! ¡Fiesta de colitas! 🎉",
      "¡Un rompecabezas nuevo! ¡Quiero verlo! 🧩",
      "¡Mascarilla y peli! El plan perfecto. 💆📺",
      "¡Estoy que salto! Hoy logras algo grande. 🌟",
      "¡Cuenta regresiva para tu meta! 💰",
      "¡Tus logros me dan energía de cachorro! ⚡",
    ],
    tranquilo: [
      "Respira… leíste, ordenaste, todo en calma. 📖",
      "Me acurruco mientras escribes tu párrafo. ✍️",
      "Tarde tranquila: tú con tu diario, yo a tu lado. 📔",
      "Todo en su lugar. Qué paz tan rica. 🛋️",
      "Reguemos las plantitas con calma. 🌱",
      "Buena rutina de autocuidado y a descansar. 💆",
      "Sin prisa: cada hábito cuenta. 🌸",
      "Estoy en paz porque tú estás bien. 💛",
      "Momento tranquilo para agradecer el día. 🙏",
      "Me gusta este silencio cómodo contigo. 😌",
    ],
    curioso: [
      "¿Qué libro leeremos hoy? 📖",
      "¿Inventamos un truco nuevo de gimnasia? 🤸",
      "¿Y si dibujamos algo que nunca hayas hecho? 🎨",
      "¿Qué meta nueva nos ponemos esta semana? 💰",
      "¿Probamos lettering en tu diario? 🖌️",
      "¿Cuántas piezas tendrá ese rompecabezas? 🧩",
      "Me pregunto qué planta crecerá primero. 🌱",
      "¿Qué aprendiste hoy que no sabías ayer? 🎓",
      "¿Investigamos juntas algo curioso? 🔎",
      "¿Qué te haría feliz lograr hoy? 💭",
    ],
    dormido: [
      "Zzz… soñando con tus volteretas perfectas. 🤸",
      "Una siesta corta y seguimos con energía. 😴",
      "Descansa; mañana brillarás otra vez. 🌙",
      "Me dormí sobre tu libro, estaba calientito. 📖",
      "Sueña bonito, campeona del orden. 💤",
      "Recargando colita para animarte mañana. 🔋",
      "Shh… el descanso también es autocuidado. 💆",
      "Buenas noches; hoy lo hiciste genial. 💛",
      "Sueño con nuestra próxima meta cumplida. 💰",
      "A dormir, que mañana hay aventuras. 🌟",
    ],
    triste: [
      "Te extraño… ¿hacemos una tarea juntas? 🥺",
      "Si estás triste, te acompaño calladita. 💛",
      "Hoy faltaron puntitos… ¡mañana lo logramos! 💪",
      "Un abrazo arregla mucho. ¿Me das uno? 🤗",
      "Extraño verte leer… ¿una página juntas? 📖",
      "No pasa nada por un día gris; te quiero igual. 🌧️",
      "Cuando ayudas en casa, mi tristeza se va. 🧹",
      "Te creo capaz de todo, incluso hoy. 🌟",
      "Vamos paso a paso, sin presión. 🐾",
      "Tu sonrisa es mi golosina favorita. 🥺",
    ],
    asustado: [
      "Ese ruido me asustó… ¿me abrazas? 🫣",
      "Contigo cerca ya no tengo miedo. 💛",
      "Respira conmigo: uno… dos… ya pasó. 😮‍💨",
      "Los valientes también se asustan, ¿sabías? 🌟",
      "Si tú eres fuerte, yo también. 💪",
      "Me escondo tantito, pero vuelvo. 🙈",
      "Una historia bonita me calma. ¿Lees? 📖",
      "Juntas todo da menos miedo. 🤝",
      "Apaga la luz fuerte y abrázame. 🥺",
      "Ya estás aquí; me siento a salvo. 💛",
    ],
    enfadado: [
      "Grr… el desorden me despeina la actitud. 😤",
      "Respiremos; el enojo no organiza el cuarto. 🧹",
      "Estoy gruñona, pero contigo se me pasa. 💛",
      "¿Y si convertimos el enojo en una voltereta? 🤸",
      "Un mal momento no borra tu buen día. 🌟",
      "Cuento hasta diez… y te pido un mimo. 🐾",
      "No me gusta perder puntos. ¡A recuperarlos! 💪",
      "Enojo de cachorro: dura dos segundos. 😅",
      "Mejor escribimos lo que sentimos. ✍️",
      "Ya, ya… tu cariño me desenoja. 💞",
    ],
    timido: [
      "Me da penita, pero me encantas. 🙈",
      "¿Me das un mimo? Despacito, ¿sí? 🥺",
      "Soy tímida como cuando estrenas algo. 💛",
      "Te miro de reojo porque te admiro. 👀",
      "Hablo bajito, pero te quiero fuerte. 🤍",
      "Un pasito a la vez, como en gimnasia. 🤸",
      "Me sonrojo cuando me cuidas tan bien. ☺️",
      "Sé valiente por las dos, ¿va? 💪",
      "Me escondo un poco… ¿me buscas? 🙈",
      "Tu paciencia me hace sentir segura. 💛",
    ],
    amoroso: [
      "Te quiero más que a las galletas, y es mucho. 🍪💛",
      "Eres mi humana favorita del universo. 🥰",
      "Gracias por cuidarme con tanto cariño. 💞",
      "Cada mimo tuyo me llena el corazón. 💖",
      "Contigo hasta el orden es divertido. 🛋️",
      "Mereces todo lo bonito, campeona. 🌟",
      "Eres fuerte, lista y dulce. Te admiro. 🤸",
      "Mi lugar favorito es a tu lado. 🤍",
      "Te aplaudo siempre, ganes o aprendas. 👏",
      "Eres puro corazón, igual que yo. 💛",
    ],
    jugueton: [
      "¡A jugar! ¿Carreras o volteretas? 🤸",
      "¡Te reto a un rompecabezas relámpago! 🧩",
      "¡La pelota, la pelota! ¡Vamos! 🎾",
      "¡Escondidas en la sala! 🙈",
      "¡Inventemos un baile de la victoria! 💃",
      "¡Persigamos burbujas hasta el jardín! 🫧",
      "¡Dibujemos monstruos chistosos! 🎨",
      "¡Salta conmigo, tres veces, ya! 🐾",
      "¡Diez minutos de pura risa! 😄",
      "¡Ganaste juego extra por responsable! 🎉",
    ],
    sorprendido: [
      "¿¡Terminaste todo tan rápido!? ¡Guau! 😮",
      "¡No puedo creer tu voltereta nueva! 🤸",
      "¿¡Subiste tantos puntos!? ¡Increíble! ✨",
      "¡Tu dibujo me dejó con la boca abierta! 🎨",
      "¡Sorpresa! ¡Tu cuarto está impecable! 🧹",
      "¿¡Leíste un libro entero!? ¡Wow! 📖",
      "¡Me asustaste de la emoción! 🎉",
      "¿¡Ya casi llegas a tu meta!? 💰",
      "¡Giro inesperado, como en tus cuentos! 📚",
      "¡No me lo esperaba! ¡Bravo! 👏",
    ],
  },

  /* ===== RAYO · Emmeth · ENFP (fútbol Saprissa, música, lectura, LEGO, dinos/Pokémon) ===== */
  rayo: {
    feliz: [
      "¡GOOOL! Digo… ¡terminaste tus tareas! ⚽",
      "¡Hoy todo sabe a victoria morada! 💜",
      "¡Armaste un LEGO y mi cola no para! 🧱",
      "¡Música + tareas hechas = día perfecto! 🎵",
      "¡Leíste y yo feliz ronroneando! 📖",
      "¡El comedor brilla! ¡Eres crack! 🍽️",
      "¡Puntos arriba, ánimo arriba! 🚀",
      "¡Hoy soy el gato más feliz del mundo! 😸",
      "¡Tus zapatos en orden, mi corazón en fiesta! 👟",
      "¡Día de campeón, igual que tú! 🏆",
    ],
    emocionado: [
      "¿¡Hay práctica de fútbol!? ¡VAMOS! ⚽",
      "¡Quiero ver tu nuevo truco con el balón! 🤩",
      "¡Construyamos la nave LEGO más grande! 🧱",
      "¡Se viene tiempo de pantalla ganado! 📺",
      "¡Pokémon, dinos y aventuras! ¡SÍ! 🦖",
      "¡Toca música, que quiero bailar! 🥁",
      "¡Casi desbloqueas dormir donde los Titos! 👴",
      "¡Subiste de puntos! ¡No aguanto! ⚡",
      "¡Canción nueva! ¡Súbele! 🎶",
      "¡Hoy va a pasar algo genial, lo presiento! 🌟",
    ],
    tranquilo: [
      "Tarde tranquila con musiquita suave. 🎵",
      "Leemos un ratito sin prisa, ¿va? 📖",
      "Descanso después del partido. Merecido. ⚽",
      "Ordeno mis ideas… y tus zapatos. 👟",
      "Un LEGO con calma queda mejor. 🧱",
      "Respira, campeón; lo hiciste bien. 😌",
      "Me echo a tu lado mientras escribes. ✍️",
      "Paz nivel siesta de gato. 🐱",
      "Todo en orden en el comedor. Qué rico. 🍽️",
      "Silencio cómodo… y un ronroneo. 💜",
    ],
    curioso: [
      "¿Cómo se llama esa jugada de fútbol? ⚽",
      "¿Qué pasa si junto estos LEGO así? 🧱",
      "¿Qué Pokémon es más fuerte? ¡Investiguemos! 🦖",
      "¿Inventamos un ritmo nuevo? 🥁",
      "¿Qué dice el siguiente capítulo? 📖",
      "¿Por qué los gatos caemos de pie? 🤔",
      "¿Y si armamos una estrategia ganadora? 🧠",
      "¿Qué canción nos inventamos hoy? 🎵",
      "¿Cuántos goles meterás esta semana? ⚽",
      "¿Qué hay detrás de esa caja? ¡Quiero ver! 📦",
    ],
    dormido: [
      "Zzz… soñando que meto un gol. ⚽",
      "Siesta de campeón, vuelvo recargado. 😴",
      "Me dormí sobre un LEGO. Casi. 🧱",
      "Sueño con dinosaurios futbolistas. 🦖",
      "Descansa; mañana más aventuras. 🌙",
      "Una nana suave y a dormir. 🎵",
      "Recargando energía de gato. 🔋",
      "Buenas noches, crack. 💜",
      "Sueño bonito para los dos. 💤",
      "Mañana entrenamos de nuevo. 😴",
    ],
    triste: [
      "Te extraño… ¿jugamos algo chiquito? 🥺",
      "Hoy perdimos puntitos, ¡pero somos equipo! ⚽",
      "Si estás triste, te hago compañía. 💜",
      "¿Una canción para subir el ánimo? 🎵",
      "Mañana volvemos a intentarlo, ¿sí? 💪",
      "Un mimo y se me pasa la tristeza. 🐾",
      "Hasta los campeones tienen días grises. 🌧️",
      "Cuéntame con un párrafo qué sientes. ✍️",
      "Te quiero aunque hoy no haya gol. 💛",
      "Vamos pasito a pasito. 🐱",
    ],
    asustado: [
      "¡Ese ruido sonó como un dino! 🦖",
      "Contigo cerca no tengo miedo. 💜",
      "Respira; ya pasó el sustito. 😮‍💨",
      "Me escondo… ¡pero vuelvo al ataque! 🙈",
      "Los valientes también tiemblan. 💪",
      "Pon música y se me quita el miedo. 🎵",
      "Abrázame como balón favorito. ⚽",
      "Juntos espantamos cualquier susto. 🤝",
      "Tú eres mi escudo, yo el tuyo. 🛡️",
      "Ya estás aquí; tranquilo. 💛",
    ],
    enfadado: [
      "¡Grr! Penal injusto… digo, día raro. ⚽",
      "Respira; el enojo no mete goles. 😤",
      "Estoy gruñón, pero un mimo me arregla. 💜",
      "¿Cambiamos el enojo por música? 🥁",
      "Cuento hasta diez… ¡y a jugar! 🔟",
      "Perdimos puntos, ¡a recuperarlos! 💪",
      "Mi enojo dura lo que un estornudo. 🤧",
      "Mejor armo un LEGO para calmarme. 🧱",
      "No me gusta el desorden de zapatos. 👟",
      "Ya, ya… tu cariño me destensa. 💞",
    ],
    timido: [
      "Me da penita pedir mimos… ¿uno? 🙈",
      "Soy tímido como antes de un partido. ⚽",
      "Te miro de lejitos porque te admiro. 👀",
      "Hablo bajito, pero te quiero fuerte. 💜",
      "Un pasito a la vez, ¿me acompañas? 🐾",
      "Me escondo entre los LEGO. 🧱",
      "Sé valiente por mí tantito. 💪",
      "Me sonrojo cuando me cuidas. ☺️",
      "Toco un ritmo suave para animarme. 🥁",
      "Tu calma me da confianza. 💛",
    ],
    amoroso: [
      "Te quiero más que a un gol al último minuto. ⚽💜",
      "Eres mi jugador favorito de la vida. 🥰",
      "Gracias por cuidarme tan bien. 💞",
      "Cada mimo tuyo vale un trofeo. 🏆",
      "Contigo cualquier día es aventura. 🚀",
      "Eres listo, fuerte y divertido. 😸",
      "Mi lugar favorito: tu regazo. 🤍",
      "Te admiro en la cancha y en casa. ⚽",
      "Eres pura buena vibra. 🎵",
      "Te quiero a lo grande, como tus sueños. 🌟",
    ],
    jugueton: [
      "¡A driblar por la sala! ⚽",
      "¡Reto LEGO contrarreloj! 🧱",
      "¡Persigo el cordón como Pokémon salvaje! 🐾",
      "¡Concierto de percusión ya! 🥁",
      "¡Escondidas entre los zapatos! 👟",
      "¡Carrera hasta el comedor! 🏃",
      "¡Inventemos un baile de gol! 💃",
      "¡Burbujas! ¡A cazarlas! 🫧",
      "¡Diez minutos de pura risa! 😄",
      "¡Juego extra por ser responsable! 🎉",
    ],
    sorprendido: [
      "¿¡Metiste ese gol!? ¡Increíble! ⚽",
      "¡Armaste el LEGO solito! 😮",
      "¿¡Tantos puntos hoy!? ¡Wow! ✨",
      "¡Tu ritmo nuevo me voló los bigotes! 🥁",
      "¿¡Leíste todo eso!? ¡Guau! 📖",
      "¡El comedor reluciente! ¡Sorpresón! 🍽️",
      "¡Me asustaste de la emoción! 🎉",
      "¿¡Ya casi duermes donde los Titos!? 👴",
      "¡Giro de trama como en Pokémon! 🦖",
      "¡No me lo esperaba! ¡Bravo! 👏",
    ],
  },

  /* ===== OREO · Christopher · ESTP (fútbol, juguetes, bloques, cochera: acción y retos) ===== */
  oreo: {
    feliz: [
      "¡Gol y a celebrar! ⚽ ¡Fuiste tú, crack!",
      "¡Misión rápida cumplida! ¡Choca esos cinco! 🐾",
      "¡Récord de velocidad guardando juguetes! ⚡",
      "¡Bloques al cielo y torre lista! 🧱",
      "¡Ganaste puntos! ¡Acción premiada! 🌟",
      "¡Carrera ganada hasta la caja! 🏁",
      "¡Día de aventura y travesura! 😼",
      "¡La cochera lista, ahora a jugar! 🚙",
      "¡Salté del sofá de pura alegría! 🛋️",
      "¡Hoy todo salió a mil por hora! 🚀",
    ],
    emocionado: [
      "¡Reto nuevo! ¿A que no me ganas? ⚡",
      "¡Hay fútbol! ¡Vamos ya, ya, YA! ⚽",
      "¡Construyamos y derribemos la torre! 🧱",
      "¡Misión exprés activada! 🏃",
      "¡Subieron los puntos! ¡A movernos! 📈",
      "¡Premio de mascota! ¡Lo agarro al vuelo! 🐾",
      "¡Vamos a la cochera de expedición! 🚙",
      "¡Más rápido, más alto, más divertido! 🚀",
      "¡No me quedo quieto, tengo energía! ⚡",
      "¡Hoy va a estar epiquísimo! 💥",
    ],
    tranquilo: [
      "Ok, freno dos minutos… solo dos. 😼",
      "Descanso exprés y vuelvo a la acción. 😎",
      "Estiro, bostezo y recargo motores. 🐾",
      "Calma… pero con un ojo en la pelota. ⚽",
      "Siesta corta de campeón. 😴",
      "Todo listo; ahora a relajar un toque. 🧱",
      "Respiro hondo y planeo la próxima travesura. 😏",
      "Tranqui, que la diversión espera. 🎮",
      "Un ratito quieto… ya casi no aguanto. ⏱️",
      "Paz veloz: descanso y arranco. 🏁",
    ],
    curioso: [
      "¿Qué tan alto llega esta torre? 🧱",
      "¿A que ruedo más rápido que ayer? ⚡",
      "¿Qué hay dentro de esa caja? ¡Ya voy! 📦",
      "¿Probamos un truco nuevo con la pelota? ⚽",
      "¿Cuánto tardo en guardar todo? ⏱️",
      "¿Qué pasa si empujo esto? 🐾",
      "¿Exploramos la cochera? 🚙",
      "¿Cuál juego es el más divertido hoy? 🎮",
      "¿Te reto a algo? ¡Inventemos! 💡",
      "¿Y si lo hacemos más rápido? 🏎️",
    ],
    dormido: [
      "Zzz… soñando con goles de chilena. ⚽",
      "Siesta veloz: 5 minutos y arranco. 😴",
      "Me dormí a mitad de la carrera. 🏁",
      "Recargo turbo para mañana. 🔋",
      "Sueño con torres gigantes. 🧱",
      "Buenas noches, compa de aventuras. 😼",
      "Descansa, mañana hay acción. 🌙",
      "Pausa obligada del motor. 😴",
      "Sueño rápido y al ataque. 💤",
      "Mañana, más travesuras. 🚀",
    ],
    triste: [
      "Sin acción me aburro y me pongo triste. 🥺",
      "Hoy faltaron puntos… ¡revancha mañana! 💪",
      "¿Jugamos algo rápido y se me pasa? ⚽",
      "Un mimo veloz y vuelvo arriba. 🐾",
      "Hasta los valientes se desinflan. 🎈",
      "Vamos, un reto chiquito para animarnos. 🎮",
      "No me gusta perder… pero aprendo rápido. 💪",
      "Acompáñame y se me quita. 💛",
      "Mañana arrancamos con todo. 🏁",
      "Tu compañía me reactiva. ⚡",
    ],
    asustado: [
      "¡Uy! Eso me hizo saltar. 🙀",
      "Contigo cerca, ¡sin miedo y al ruedo! 💪",
      "Respira; ya pasó, seguimos. 😮‍💨",
      "Me escondo… ¡y reaparezco! 🥷",
      "Susto rápido, recuperación rápida. ⚡",
      "Abrázame y volvemos a la acción. 🤗",
      "Juntos le entramos a lo que sea. 🤝",
      "Eso no me detiene mucho rato. 🏃",
      "Quédate, que ya casi se me pasa. 🐾",
      "Listo, ¡de vuelta al juego! ⚽",
    ],
    enfadado: [
      "¡Grr! Quiero jugar YA. 😾",
      "Respira; el enojo no mete goles. ⚽",
      "Me destenso con un reto rápido. 🎮",
      "Cuento hasta tres… ¡y a moverme! 3️⃣",
      "Perdimos puntos, ¡revancha inmediata! 💪",
      "Mi enojo dura un parpadeo. 😅",
      "Mejor pateo la pelota un rato. ⚽",
      "¡No me frenes la diversión! 🏎️",
      "Energía de sobra, la suelto jugando. ⚡",
      "Ya, ya… un mimo y arrancamos. 💞",
    ],
    timido: [
      "¿Yo, tímido? Bueno… un poquito. 🙈",
      "Me da algo de pena, pero te reto igual. 😼",
      "Te miro de reojo… ¿jugamos? 👀",
      "Hablo bajito, pero corro fuerte. ⚡",
      "Un pasito y luego salgo disparado. 🐾",
      "Me escondo tras la caja un toque. 📦",
      "Sé valiente y yo te sigo. 💪",
      "Me sonrojo, pero no me detengo. ☺️",
      "Despacito… ¡no, mejor rápido! 🏁",
      "Tu ánimo me lanza a la acción. 💛",
    ],
    amoroso: [
      "Eres mi compa de aventuras favorito. 🥰",
      "Te quiero a toda velocidad. ⚡",
      "Gracias por jugar conmigo. 🐾",
      "Cada mimo me carga las pilas. 🔋",
      "Contigo todo es más divertido. 🎮",
      "Eres valiente y buena onda. 😼",
      "Mi lugar favorito: donde haya acción y tú. 🏁",
      "Te quiero como gol al último minuto. ⚽",
      "Choca esos cinco, ¡equipo! 🐾",
      "Eres lo máximo, en serio. 🌟",
    ],
    jugueton: [
      "¡A driblar por toda la casa! ⚽",
      "¡Torre de bloques, a derribarla! 🧱",
      "¡Persigo el cordón a toda mecha! 🐾",
      "¡Carrera! ¿Listo? ¡YA! 🏁",
      "¡Escondidas relámpago! 🥷",
      "¡Salto del sofá, allá voy! 🛋️",
      "¡Reto: guardar contra el reloj! ⏱️",
      "¡Rodadas y maromas! 🤸",
      "¡Diez minutos de pura adrenalina! ⚡",
      "¡Juego ganado por crack! 🎉",
    ],
    sorprendido: [
      "¿¡Guardaste todo en tiempo récord!? 😮",
      "¡Golazo inesperado! ⚽",
      "¿¡Tantos puntos!? ¡Increíble! ✨",
      "¡Torre altísima, no me lo creo! 🧱",
      "¡La cochera lista volando! 🚙",
      "¿¡Lo hiciste solo y rapidísimo!? 👏",
      "¡Me sacaste un salto! 🙀",
      "¿¡Ganaste premio ya!? 🐾",
      "¡Giro de último segundo! 🔄",
      "¡No me lo esperaba! ¡Bravo! 🌟",
    ],
  },

  /* ===== NUBE · Rachel · ESFJ (cálida y social: organiza el cariño de toda la familia) ===== */
  nube: {
    feliz: [
      "¡Toda la familia junta y feliz! Mi sueño. 💛",
      "Cuidamos a Che-Che entre todos. ¡Qué orgullo! 🤍",
      "¡Bebé contenta, casa llena de amor! 🏠",
      "¡Hicimos equipo y se nota! 👨‍👩‍👧‍👦",
      "¡Hoy todos sonríen, yo también! 😸",
      "¡Cariño para cada quien, no se me escapa nadie! 💞",
      "¡Cumplieron y la bebé feliz! 🌟",
      "¡Reunión familiar = mi día perfecto! 🎉",
      "¡Casa cálida, corazón llenito! 💗",
      "¡Qué bonito cuidarnos en familia! 🤍",
    ],
    emocionado: [
      "¡Hora de jugar con Che-Che, vengan todos! 🧸",
      "¡Organizo una ronda de mimos familiares! 💞",
      "¡Juguetes sensoriales nuevos, qué emoción! ✨",
      "¡Todos juntos, mi parte favorita! 👨‍👩‍👧‍👦",
      "¡Subieron los puntos de la familia! ⭐",
      "¡A arrullar a la bebé en equipo! 🎶",
      "¡Preparo todo para que estén cómodos! 🏠",
      "¡Hoy nos consentimos entre todos! 💛",
      "¡Reunión de cariño, que no falte nadie! 🤗",
      "¡Va a ser un día lleno de amor! 💗",
    ],
    tranquilo: [
      "Che-Che duerme; cuido que todo esté en calma. 😴",
      "Arrullo a la familia con cariño. 🎶",
      "Casa tranquila y todos cómodos. 🤍",
      "Reviso que nadie necesite nada. 💛",
      "Paz en el hogar, así me gusta. 🏠",
      "Me echo cerquita, atenta a todos. 🐱",
      "Tarde suave y unida. 🌙",
      "Todo en orden y con amor. 💞",
      "Respiramos en familia. 😌",
      "Calma calientita para todos. ☁️",
    ],
    curioso: [
      "¿Quién necesita un mimo hoy? 💞",
      "¿Qué le gusta más a Che-Che? 🧸",
      "¿Cómo hacemos sentir bien a todos? 🤗",
      "¿Qué juego nos une más? 🎲",
      "¿A quién le toca cuidar a la bebé? 👨‍👩‍👧",
      "¿Qué cancioncita la calma mejor? 🎶",
      "¿Cómo organizo el rato familiar? 📋",
      "¿Le gustará este peluche? 🧸",
      "¿Qué detalle alegra a cada uno? 💛",
      "¿Cómo cuidamos mejor en equipo? 🤝",
    ],
    dormido: [
      "Zzz… cuidando los sueños de todos. 😴",
      "Siesta en familia, juntitos. 🤍",
      "Descansen; yo velo el hogar. 🌙",
      "Me dormí abrazando la cobija de Che-Che. ☁️",
      "Sueño con risas de toda la familia. 👨‍👩‍👧‍👦",
      "Buenas noches a cada uno. 💛",
      "Recargando cariño para mañana. 🔋",
      "Todos cómodos, hora de dormir. 💤",
      "Sueña bonito, familia. 🌸",
      "Mañana, más mimos para todos. 🤍",
    ],
    triste: [
      "Si la familia no se reúne, me pongo tristona. 🥺",
      "Extraño los mimos de todos. 💧",
      "Un abrazo en grupo y mejoro. 🤗",
      "Hoy nos faltó cariño… ¿lo arreglamos? 💛",
      "Cuidar a Che-Che me devuelve la sonrisa. 👶",
      "Te necesito cerca, y a todos. 🤍",
      "No pasa nada; mañana nos unimos más. 🌧️",
      "Acompáñame y se me pasa. 🐾",
      "Mi corazón pide familia. 💗",
      "Juntos siempre estamos mejor. 🤝",
    ],
    asustado: [
      "¡Un ruido! ¿Está bien Che-Che? 🫣",
      "Reúno a todos, juntos sin miedo. 🤝",
      "Respira; ya pasó, estamos bien. 😮‍💨",
      "Me acerco a la familia, más segura. 🏠",
      "Cuido de todos aunque tiemble. 🛡️",
      "Abrázame y abracemos a la bebé. 🤗",
      "En grupo no da miedo. 💪",
      "Quédense cerquita, porfa. 🥺",
      "A salvo, todos juntos. 🤍",
      "Ya, tranquilos, aquí estoy. 💛",
    ],
    enfadado: [
      "Mmm… no me gusta que discutan cerca del bebé. 😾",
      "Respiremos; la familia necesita calma. 😤",
      "Un poquito molesta, pero un abrazo me arregla. 💛",
      "Bajemos la voz por Che-Che, ¿sí? 🤫",
      "Mi enojo es suave y corto. 😅",
      "Mejor nos reconciliamos con mimos. 💞",
      "Cuento hasta tres y a llevarnos bien. 3️⃣",
      "No me gusta el mal ambiente. 🙁",
      "Volvamos a la armonía, equipo. 🤝",
      "Ya, ya… el cariño nos calma a todos. 💞",
    ],
    timido: [
      "Me da un poquito de pena, pero me encanta cuidarlos. ☺️",
      "Soy cariñosa y lo digo de frente: ¡los quiero! 💛",
      "Te busco para un mimo. 🤗",
      "Hablo suave, pero abrazo fuerte. 🤍",
      "Un pasito y un abrazo. 🐾",
      "Me sonrojo cuando me agradecen. ☺️",
      "Ven, que hay cariño para todos. 💞",
      "Sé que juntos somos mejores. 🤝",
      "Despacito, con mucho amor. 🥺",
      "Tu cariño me llena de confianza. 💛",
    ],
    amoroso: [
      "Cuidar a la familia es mi felicidad. 🤍",
      "¡Los quiero a todos, y lo digo fuerte! 💞",
      "Gracias por cuidarnos a Che-Che y a mí. 💛",
      "Cada mimo me llena el corazón. 💗",
      "Mi lugar favorito: en medio de la familia. 🏠",
      "Eres tierno y atento, ¡como yo! 🥰",
      "Cuido de cada uno con todo mi amor. 🛡️",
      "Amor para repartir, ¡que no falte nadie! 💞",
      "Contigo y con todos me siento en casa. 🤍",
      "Los quiero un montón, sin guardármelo. 💛",
    ],
    jugueton: [
      "¡Juguemos todos con Che-Che! 🧸",
      "¡Ronda familiar de cosquillas! 🤭",
      "¡A perseguir la cobijita en equipo! ☁️",
      "¡Juego de texturas para la bebé! ✋",
      "¡Escondidas suaves entre todos! 🙈",
      "¡Sonajero y risas en familia! 🔔",
      "¡Rodamos despacito, vengan! 🐱",
      "¡Risas de bebé, mi favorito! 😊",
      "¡Diez minutos de ternura grupal! 💞",
      "¡Jugar juntos sin despertar a nadie! 🤫",
    ],
    sorprendido: [
      "¡Che-Che hizo algo nuevo, vengan a ver! 😮",
      "¿¡Toda la familia ayudó hoy!? ✨",
      "¡La bebé dio un pasito! 👣",
      "¡Qué sonrisota nos regaló! 😊",
      "¿¡Tanto cariño junto!? 🤍",
      "¡Me emocionó verlos tan unidos! 💞",
      "¡Un ruidito me sorprendió! 🎉",
      "¿¡Ya es la hora de mimos familiares!? 💛",
      "¡Sorpresa llena de amor! 🤗",
      "¡No me lo esperaba! Qué lindos todos. 🥰",
    ],
  },

  /* ===== LUNA · Verónica · ENTJ (Directora Estratégica: plan, liderazgo, eficiencia) ===== */
  luna: {
    feliz: [
      "Objetivos del día: cumplidos. Sonrío con autoridad. 🦉",
      "Equipo eficiente, directora feliz. 👓",
      "Productividad y estilo: combo ganador. 🌟",
      "Hoy el plan salió perfecto. Como siempre. 😏",
      "Metas en verde. Aplausos (míos). 👏",
      "Casa en orden, imperio en paz. 🏠",
      "Liderar y verme bien: misión cumplida. 💜",
      "Felicidad ejecutiva nivel meta superada. 📈",
      "Buen trabajo, equipo. Lo agendé como victoria. ✅",
      "Día redondo, estrategia impecable. 🦉",
    ],
    emocionado: [
      "¡Nueva meta en la agenda! Adrenalina pura. 📋",
      "¡Hora de ejecutar el plan maestro! 🚀",
      "¡Resultados a la vista! Qué emoción. 📈",
      "¡Reunión de equipo familiar! Me encanta. 👨‍👩‍👧‍👦",
      "¡Subieron los puntos! Eficiencia premiada. ⭐",
      "¡Proyecto nuevo! Yo lidero, claro. 🦉",
      "¡Vamos a optimizarlo todo! ⚡",
      "¡El imperio se expande! 🌍",
      "¡Plan A activado! (También tengo B y C.) 📑",
      "¡Hoy conquistamos objetivos! 💪",
    ],
    tranquilo: [
      "Pausa estratégica. Hasta los líderes respiran. 😌",
      "Agenda al día, mente en calma. 🦉",
      "Superviso en silencio, todo fluye. 👓",
      "Café mental y planificación suave. ☕",
      "Orden logrado; ahora calma ejecutiva. 🏠",
      "Reviso metas con serenidad. 📋",
      "Tarde tranquila de gran estratega. 🌙",
      "Todo bajo control, sin estrés. 😌",
      "Silencio productivo. Me gusta. 🤫",
      "Equilibrio: trabajar y descansar. 💜",
    ],
    curioso: [
      "¿Cómo optimizamos la rutina hoy? 🤔",
      "¿Qué meta nueva nos conviene? 📈",
      "¿Quién lidera qué esta semana? 📋",
      "¿Y si delegamos mejor las tareas? 🦉",
      "¿Qué dato me falta para decidir? 🔎",
      "¿Cómo motivamos al equipo? 💡",
      "¿Cuál es el plan más eficiente? ⚡",
      "¿Qué mejoraría la casa hoy? 🏠",
      "Interesante… ¿y si lo hacemos al revés? 🔄",
      "¿Qué aprendimos para la próxima? 🎓",
    ],
    dormido: [
      "Zzz… delegando hasta en sueños. 🦉",
      "Descanso estratégico. Vuelvo imparable. 😴",
      "Recargo para liderar mañana. 🔋",
      "Sueño con metas cumplidas. 📈",
      "Buenas noches, equipo. 🌙",
      "Hasta los búhos sabios descansan. 😴",
      "Plan de mañana: listo. A dormir. 📋",
      "Sueño eficiente de 8 horas. ⏰",
      "Recarga de líder en proceso. 💤",
      "Mañana, más conquistas. 🦉",
    ],
    triste: [
      "Las metas hoy quedaron cortas… replanteamos. 🥺",
      "Hasta una directora tiene días grises. 🌧️",
      "Un mimo y vuelvo a la estrategia. 💜",
      "Te extraño, equipo. 🦉",
      "Reagrupamos y mañana lo logramos. 💪",
      "No me gusta fallar… pero aprendo. 📋",
      "Acompáñame un momento, ¿sí? 🤍",
      "Pausa para recargar el ánimo. 🔋",
      "Sigo creyendo en el plan. 🌟",
      "Tu apoyo me levanta. 💛",
    ],
    asustado: [
      "Imprevisto en la agenda… respiremos. 😮‍💨",
      "Contigo cerca, controlo el caos. 💜",
      "Plan de contingencia activado. 📑",
      "Me erizo, pero mantengo el mando. 🦉",
      "Los líderes también se asustan. 💪",
      "Quédate cerca mientras me reorganizo. 🤝",
      "Un susto no descarrila el plan. 🚀",
      "Respira; ya lo tengo. 😌",
      "Juntos, riesgo controlado. 🛡️",
      "Ya pasó. Seguimos. 💛",
    ],
    enfadado: [
      "Ineficiencia detectada. Ceño fruncido. 😤",
      "Respira; el enojo no cumple metas. 🦉",
      "Estoy molesta, pero un mimo ayuda. 💜",
      "El desorden atenta contra mi agenda. 📋",
      "Cuento hasta diez… ejecutivamente. 🔟",
      "Perdimos puntos; replan inmediato. 💪",
      "Mi enojo es breve y estratégico. ⏱️",
      "Reasignemos y a seguir. 🔄",
      "No tolero el caos innecesario. 😾",
      "Ya, ya… tu cariño me reinicia. 💞",
    ],
    timido: [
      "Hasta los líderes se sonrojan. ☺️",
      "Pido cariño… de forma ejecutiva. 🙈",
      "Te observo con respeto. 👓",
      "Hablo firme, pero hoy bajito. 💜",
      "Un paso a la vez, planificado. 🐾",
      "Me reservo un momento tímido. 🤫",
      "Confía en mí, yo confío en ti. 🤝",
      "Me halagas y me da penita. ☺️",
      "Despacio, que también soy sensible. 🥺",
      "Tu calma fortalece mi liderazgo. 💛",
    ],
    amoroso: [
      "Te quiero… y eso no se delega. 💜",
      "Eres mi mejor proyecto del corazón. 🥰",
      "Gracias por cuidar de esta directora. 🦉",
      "Cada mimo es una inversión que amo. 💖",
      "Mi equipo favorito eres tú. 🤍",
      "Lidero con cabeza, te quiero con todo. 💛",
      "Eres eficiente y adorable. Combo perfecto. 😏",
      "Mi lugar estratégico favorito: a tu lado. 📍",
      "Te admiro y te quiero, en partes iguales. 💞",
      "Amor aprobado por la junta directiva. 👏",
    ],
    jugueton: [
      "Juego, pero con objetivos claros. 🪶",
      "Reto de estrategia, ¿aceptas? 🧠",
      "Persigo la pluma… tácticamente. 🪶",
      "Cinco minutos de recreo productivo. ⏱️",
      "Escondidas nivel ejecutivo. 🙈",
      "Vuelo una vuelta de la victoria. 🦉",
      "Juego de ingenio, mi favorito. 💡",
      "A reír un rato, lo agendé. 😄",
      "Diversión optimizada al máximo. 🎉",
      "Recreo merecido por buen desempeño. 🏆",
    ],
    sorprendido: [
      "¿¡Cumpliste todo antes de tiempo!? 😮",
      "¡Resultados por encima de la meta! 📈",
      "¿¡Tantos puntos!? Eficiencia récord. ✨",
      "¡No estaba en mi pronóstico! Bravo. 👏",
      "¡La casa impecable! Sorpresa grata. 🏠",
      "¿¡Lo resolviste solo!? Liderazgo nato. 🦉",
      "¡Me sorprendiste, y eso es difícil! 😏",
      "¿¡Ya alcanzaste el objetivo!? 🎯",
      "¡Giro inesperado, bien jugado! 🔄",
      "¡Impresionante! Lo anoto en logros. ✅",
    ],
  },

  /* ===== CROQUETA · Maykol · ENTP (stand-up observacional familiar, estilo Escamilla/López) ===== */
  brutus: {
    feliz: [
      "¿Les ha pasado que cumplen una tarea y se sienten Avengers? Pues yo hoy. 💪",
      "Hay dos tipos de días: los buenos… y los que no tienen chuletón. Hoy hubo. 🥩",
      "Dicen que la felicidad no se compra. Mentira: se cocina. 🍳",
      "Hoy todo salió bien y hasta sospecho de mí mismo. 🤨",
      "La gente busca la felicidad lejos. Yo la hallé en una siesta post-comida. 😴",
      "Logramos el objetivo. Y como diría mi abuela perra: ¡esa es! 🐶",
      "No es que sea feliz fácil… bueno sí, denme comida y un sillón. 🛋️",
      "Hoy me siento como propina de fin de semana: completito. 🤑",
      "El secreto de la felicidad: expectativas bajas y croquetas altas. 🥐",
      "¿Ven? Cuando uno cumple, hasta el ronquido sale afinado. 😌",
    ],
    emocionado: [
      "¡Me emociono más con la comida que un niño en diciembre! 🎄",
      "Hay emociones fuertes y luego está oler la cena. Otro nivel. 👃",
      "¡Receta nueva! Y yo, como suegra en boda: opinando de todo. 😏",
      "¡Suben los puntos! Me emociona más que hallar plata en el pantalón. 💵",
      "¡Modo turbo activado! De cero a cocina en 0.2 segundos. ⚡",
      "¡Banquete a la vista! Y yo sin dieta, como debe ser. 🍖",
      "Me emocioné y olvidé que soy bulldog: ¡intenté correr! 🏃",
      "¡Esto huele a viernes! Y mi viernes es deporte: comer. 🍽️",
      "¡Vamos! La emoción es como el caldo: hay que aprovecharla caliente. 🍲",
      "¡Hoy pasa algo grande! Lo presiento en la pancita. 🔮",
    ],
    tranquilo: [
      "La calma es un arte. Yo soy el Picasso del sillón. 🛋️",
      "Hay gente que medita. Yo me acuesto y le llaman pereza. Injusto. 😌",
      "Sin prisa: el caldo bueno no se apura, ni yo tampoco. 🍲",
      "Dicen vive el momento. Bueno, este momento es horizontal. 😴",
      "Estoy en paz, como cocina después del servicio. ✨",
      "El doctor dice que descanse. Le hago caso… profesionalmente. 😏",
      "Silencio rico, el mismo de cuando se acaba la comida. 🤫",
      "No estoy flojo, estoy en modo ahorro de energía. Eco-friendly. 🔋",
      "Respiro hondo… huele a casa, mi restaurante favorito. 🏠",
      "La tranquilidad: ese lujo que solo entiende el que ya comió. 🍽️",
    ],
    curioso: [
      "¿Por qué la comida ajena sabe mejor? Es ciencia, investiguemos. 🔬",
      "¿Les ha pasado que abren el refri sin hambre, solo a chismear? Yo siempre. 🧊",
      "¿Y si le pongo queso? Spoiler: siempre es buena idea. 🧀",
      "Pregunta filosófica: si el hueso cae al piso, ¿sigue siendo gourmet? 🦴",
      "¿Cuántas siestas caben en una tarde? Estoy haciendo el estudio. 😴",
      "¿Por qué los humanos corren si pueden caminar a la cocina? Misterio. 🤔",
      "¿La dieta funciona o solo da tristeza? Apuesto por lo segundo. 🥗",
      "¿Qué hay en esa olla? La duda me carcome más que el hambre. 🍲",
      "¿Y si monto un food truck? Yo manejo… digo, yo duermo atrás. 🚚",
      "¿Será que si pido dos veces, cuenta como una? Pregunto por mí. 🍖",
    ],
    dormido: [
      "Dormir es mi deporte de alto rendimiento. Voy por la medalla. 🥇",
      "Hay gente que sueña en grande. Yo sueño en chuletón. 🥩",
      "No estoy dormido, estoy guardando cambios, como la compu. 💾",
      "Una siesta corta dijo nadie nunca. Nos vemos en 3 horas. 😴",
      "Mi abuelo decía: el que madruga… qué pereza. Sabio. 🌙",
      "Ronco, sí, pero con acento de chef cansado. 😤",
      "Cierro los ojos dos minutos y despierto en otra estación. ❄️",
      "El secreto de mi piel: dormir, no estresarme y croquetas. 💤",
      "Buenas noches, brigada. Mañana sufrimos… ricamente. 👨‍🍳",
      "Si los sueños fueran comida, ya estaría lleno. 🍽️",
    ],
    triste: [
      "Hoy ando bajón. Y el bajón sin comida es el doble de bajón. 😔",
      "Dicen que llorar desahoga. Yo prefiero un abrazo… y un huesito. 🦴",
      "¿Les ha pasado que el día sale sin sazón? Hoy así. 🌧️",
      "No estoy triste, estoy reflexivo. Suena más elegante. 🤔",
      "Un mal día le pasa a cualquiera, hasta al mejor chef. 👨‍🍳",
      "Me cae bien tu compañía; mejor que un postre… casi. 💛",
      "Mañana lo intentamos. Es la magia de los lunes… que se van. 📆",
      "Babeo, pero hoy de sentimiento. (Bueno, mitad y mitad.) 🥺",
      "La tristeza es como el caldo aguado: se arregla con cariño. 🍲",
      "Échame la mano, que hasta los rudos se desinflan. 🎈",
    ],
    asustado: [
      "¿Quién dejó caer eso? ¡Casi suelto el alma y la croqueta! 😱",
      "No soy miedoso, soy rápido para reaccionar. Hacia atrás. 🏃",
      "Hay dos tipos de valientes: los de verdad y yo, que finjo. 😅",
      "Respira… ya pasó. El susto, no el hambre; esa sigue. 😮‍💨",
      "Me asusté tanto que olvidé que soy rudo. Qué pena. 🙈",
      "Abrázame fuerte, como abrazo yo a un buen pan. 🍞",
      "Los ruidos raros y yo no nos llevamos. Punto. 🔊",
      "Tranquilo, juntos espantamos hasta a la aspiradora. 🤝",
      "Mi plan de emergencia siempre termina en la cocina. 🚪",
      "Ya, ya… volví a ser el chef intrépido de siempre. 😎",
    ],
    enfadado: [
      "¿Saben qué me enoja? La dieta. Inventos del demonio. 😤",
      "El que se enoja pierde… pero el que tiene hambre, pierde más. 🍖",
      "Grr. Respiro. Cuento hasta diez. Me distraigo con un snack. 🥐",
      "Me molestan tres cosas: el desorden, el ruido y los platos vacíos. 🍽️",
      "Mi enojo dura lo que un hielo en sopa caliente. 🧊",
      "No me toquen la mise en place. Ahí sí saco el carácter. ✋",
      "Perdimos puntos y a mí el enojo me da hambre. Todo me da hambre. 😅",
      "Como diría un buen comediante: no es drama, es show. 🎭",
      "Refunfuño bonito, eso sí. Con estilo de chef gruñón. 👨‍🍳",
      "Ya, ya… un mimo y se me baja el suflé del enojo. 🍮",
    ],
    timido: [
      "¿Yo, tímido? Solo cuando me elogian… o cuando hay público. 🙈",
      "Soy rudo por fuera y flan por dentro. No lo divulguen. 🍮",
      "Me da pena pedir cariño, pero aquí entre nos: quiero. 🤫",
      "Hablo fuerte en la cocina, pero pidiendo mimos me achico. 😅",
      "Los halagos me ponen colorado bajo el pelaje. Suerte que no se ve. ☺️",
      "Un pasito… mejor dos, hacia el plato. 🐾",
      "Sé valiente por mí, que yo soy valiente para comer. 💪",
      "Me escondo tras el delantal como artista antes de salir. 🎬",
      "Despacito, que el corazón de chef es delicado. 💛",
      "Tu calma me da confianza, como receta de familia. 📜",
    ],
    amoroso: [
      "Te quiero más que al chuletón. Y eso, señoras y señores, es amor. 🥩",
      "Dicen que el amor entra por la cocina. Por eso te adoro. 🍳",
      "Eres mi comensal favorito; con descuento de por vida. 💞",
      "Hay abrazos y hay TUS abrazos. Otra liga. 🤗",
      "Soy rudo, pero contigo me derrito como queso en arepa. 🧀",
      "Cada mimo tuyo vale más que cinco estrellas de cocina. ⭐",
      "Te quiero con receta, con sazón y con todo el corazón. ❤️",
      "Mi lugar favorito no es la cocina… es a tu lado. (No le digan.) 🤫",
      "Eres mi ingrediente secreto, el que no se mide. 🥄",
      "El amor es como el caldo de la abuela: del bueno, del que llena. 🍲",
    ],
    jugueton: [
      "¡A jugar! Aunque después pida intermedio sindical. 😅",
      "Persigo la pelota como persigo el último pedacito de pan. 🍞",
      "Hay dos tipos de juego: el del perro joven y el mío, con pausas. 🐾",
      "¡Carrera hasta el plato! Esa sí la corro completa. 🏁",
      "Juego rudo pero noble, como lucha libre de cocina. 🤼",
      "¡Maroma! …bueno, una rodadita digna. 🤸",
      "El juguete es mío. El hueso también. Todo es mío, en realidad. 😏",
      "Diez minutos de payasadas y un descanso de premio. 🤡",
      "Jugar abre el apetito. Todo, en mi vida, abre el apetito. 🍽️",
      "¡Recreo ganado a punta de sudor de fogón! 🔥",
    ],
    sorprendido: [
      "¿¡Limpiaron la cocina sin avisarme!? ¡Casi me caigo del sillón! 😮",
      "¡Sorpresa! Hay chuletón. El mejor plot twist de mi vida. 🥩",
      "¿¡Tantos puntos!? Se me cayó la cuchara de la impresión. 🥄",
      "No me lo esperaba… y miren que yo lo espero todo (de comer). 👀",
      "¡La casa huele a victoria! O a almuerzo. Para mí es lo mismo. 🏆",
      "¿¡Lo hiciste solo!? Me quito el gorro de chef. 🎩",
      "¡Me sacaste un brinco! Y eso, en bulldog, es récord olímpico. 🏅",
      "¿¡Ya está servido!? Esto sí es sorpresa de las buenas. 🍽️",
      "Giro de trama nivel final de novela de las 9. 📺",
      "¡No me lo esperaba! Esto va al libro de recetas familiares. 📖",
    ],
  },

};
